name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fitcrew_focus
    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/fitcrew_focus
      DIRECT_URL: postgresql://postgres:postgres@localhost:5432/fitcrew_focus
      APP_URL: http://127.0.0.1:3100
      JWT_SECRET: ci-dev-secret-key-please-change-1234567890
      AI_COMMENT_CRON_SECRET: ci-cron-secret-token
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: fitcrew-focus/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: fitcrew-focus
        run: pnpm install --frozen-lockfile

      - name: Env check
        working-directory: fitcrew-focus
        run: pnpm run env:check

      - name: Generate Prisma client
        working-directory: fitcrew-focus
        run: pnpm prisma:generate

      - name: Apply migrations
        working-directory: fitcrew-focus
        run: pnpm prisma migrate deploy

      - name: Seed database
        working-directory: fitcrew-focus
        run: pnpm prisma:seed

      - name: Typecheck
        working-directory: fitcrew-focus
        run: pnpm typecheck

      - name: Lint
        working-directory: fitcrew-focus
        run: pnpm lint

      - name: Tests
        working-directory: fitcrew-focus
        run: pnpm test -- --run

      - name: Build
        working-directory: fitcrew-focus
        run: pnpm build

      - name: Smoke API
        working-directory: fitcrew-focus
        run: pnpm smoke:api

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: fitcrew-focus/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: fitcrew-focus
        run: pnpm install --frozen-lockfile

      - name: Pull Vercel env
        working-directory: fitcrew-focus
        run: pnpm dlx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        working-directory: fitcrew-focus
        run: pnpm dlx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        working-directory: fitcrew-focus
        run: pnpm dlx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
